# Generated by Django 5.0.4 on 2024-04-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=50)),
                ('address_number', models.IntegerField()),
                ('address_city', models.CharField(max_length=40)),
                ('address_country', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=13)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
                ('material_description', models.CharField(max_length=255)),
                ('material_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=40)),
                ('required_skills', models.CharField(max_length=300)),
                ('certifications', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_name', models.CharField(max_length=60)),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.address')),
            ],
        ),
        migrations.CreateModel(
            name='Userr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=13)),
                ('skills', models.CharField(blank=True, max_length=500, null=True)),
                ('password_user', models.CharField(max_length=30)),
                ('role_user', models.CharField(max_length=1)),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.address')),
                ('id_profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=40)),
                ('task_description', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_status', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_creation', models.DateField()),
                ('date_of_completion', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.client')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.userr')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date_work_record', models.DateField(blank=True, null=True)),
                ('id_place_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.placeofwork')),
                ('id_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weblog.task')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.userr')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('id_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.materials')),
                ('id_work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.workrecord')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField()),
                ('old_description', models.CharField(max_length=2000)),
                ('new_description', models.CharField(max_length=2000)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.userr')),
                ('id_work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.workrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
