# Generated by Django 5.0.4 on 2024-04-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_address_client_materials_profession_placeofwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='role_user',
            field=models.CharField(choices=[('V', 'Veduci'), ('Z', 'Zamestnanec')], max_length=20),
        ),
    ]
