# Generated by Django 5.0.4 on 2024-05-06 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_alter_userr_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_place_of_work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weblog.placeofwork'),
        ),
    ]
